version: "2"
services:
  proxy:
    image: diogok/caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./config:/etc/biodiv
      - /opt/caddy:/root/.caddy
  biodivui:
    image: diogok/biodiv-ui
    environment:
      INDEX: dwc
      ELASTICSEARCH: http://elasticsearch:9200
  biodividx:
    image: diogok/biodiv-idx
    environment:
      INDEX: dwc
      ELASTICSEARCH: http://elasticsearch:9200
      DWC_SERVICES: http://dwcservices/api/v1
  taxabot:
    image: diogok/taxa-bot
    environment:
      INDEX: dwc
      ELASTICSEARCH: http://elasticsearch:9200
    volumes:
      - ./config:/etc/biodiv
  dwcbot:
    image: diogok/dwc-bot-es
    environment:
      INDEX: dwc
      ELASTICSEARCH: http://elasticsearch:9200
    volumes:
      - ./config:/etc/biodiv
  dwcservices:
    image: diogok/dwc-services
  elasticsearch:
    image: diogok/elasticsearch
    volumes:
      - /var/data/dwc-elasticsearch/data:/usr/share/elasticsearch/data:rw
  kibana:
    image: diogok/kibana
    environment:
      BASE: kibana
