version: "2"
services:
  proxy:
    image: diogok/caddy
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - /opt/caddy:/root/.caddy
      - ./config:/etc/biodiv
  ui:
    image: diogok/rrapp-ui
    volumes:
      - ./config:/etc/biodiv
  idx:
    image: diogok/rrapp-idx
    volumes:
      - ./config:/etc/biodiv
  bot:
    image: diogok/dwc-bot-es
    volumes:
      - ./config:/etc/biodiv
  elasticsearch:
    image: diogok/elasticsearch
    volumes:
      - /var/data/dwc-elasticsearch/data:/usr/share/elasticsearch/data:rw
  kibana:
    image: diogok/kibana
    environment:
      BASE: kibana
