version: "2"
services:
  proxy:
    image: diogok/caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./config:/etc/biodiv
      - /opt/caddy:/root/.caddy
    networks:
      - biodiv
  biodivui:
    image: diogok/biodiv-ui
    volumes:
      - ./config:/etc/biodiv
    networks:
      - biodiv
  biodividx:
    image: diogok/biodiv-idx
    volumes:
      - ./config:/etc/biodiv
    networks:
      - biodiv
  taxadata:
    image: diogok/taxadata
    volumes:
      - ./config:/etc/biodiv
    networks:
      - biodiv
  ipt:
    image: diogok/ipt
    networks:
      - biodiv
  dwcbot:
    image: diogok/dwc-bot
    volumes:
      - ./config:/etc/biodiv
    environment:
      PROXY: "/dwc-bot"
    volumes:
      - /var/data/dwc-bot:/var/data/dwc-bot:rw
    networks:
      - biodiv
  dwcservices:
    image: diogok/dwc-services
    networks:
      - biodiv
    environment:
      PROXY: "/dwc-services"
  elasticsearch:
    image: diogok/elasticsearch
    networks:
      - biodiv
    volumes:
      - /var/data/dwc-elasticsearch/data:/usr/share/elasticsearch/data:rw
networks:
  biodiv:
