version: "2"
services:
  proxy:
    image: diogok/caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./config:/etc/biodiv
      - /opt/caddy:/root/.caddy
  biodivui:
    image: diogok/biodiv-ui
    environment:
      INDEX: ${INDEX}
      ELASTICSEARCH: ${ELASTICSEARCH}
  biodividx:
    image: diogok/biodiv-idx
    environment:
      INDEX: ${INDEX}
      ELASTICSEARCH: ${ELASTICSEARCH}
  dwcbot:
    image: diogok/dwc-bot-es
    environment:
      INDEX: ${INDEX}
      ELASTICSEARCH: ${ELASTICSEARCH}
    volumes:
      - ./config:/etc/biodiv
  elasticsearch:
    image: diogok/elasticsearch
    volumes:
      - /var/data/dwc-elasticsearch/data:/usr/share/elasticsearch/data:rw
  kibana:
    image: diogok/kibana
    environment:
      BASE: kibana
